### ISSUE TITLE
concluding statement

### ISSUE THREAD

**Issue by andrew-zentner** [andrew-zentner/abmcmc#26]
as suggested by @aphearin : 
here's a spitball for a strong statement to end on. something along the lines of how accounting for assembly bias is not optional if cosmological precision is desired, that our results demonstrate that necessity, and that we have just given an explicit example of the way forward.

**Comment by aphearin** [comment]
The concluding statement introduced in https://github.com/andrew-zentner/abmcmc/commit/eae3f0640c1ca04774d0f5ac656277f325f14594 by @andrew-zentner looks solid to me.

**Comment by aphearin** [comment]
In https://github.com/andrew-zentner/abmcmc/commit/eae3f0640c1ca04774d0f5ac656277f325f14594 you also introduce an entirely new _Section_ dedicated to _Interpretation_. However, I think this is probably not warranted since we really only need a paragraph or two here, so maybe consider having _Interpretation_ be a subsection of the Conclusions?

I'm taking a stab at composing a few paragraphs for this purpose now.

**Comment by andrew-zentner** [comment]
Concluding paragraph now in draft.
