### ISSUE TITLE
Labels in Figs 1, 5, 6 and 7 dont match table 2

### ISSUE THREAD

**Issue by vdbosch69** [andrew-zentner/abmcmc#35]
The labels above the 1D posteriors in Figs 1, 5 , 6 and 7 are NOT in agreement with the
percentiles quoted in the Table!!! Differences can be very substantial in some cases.....

**Comment by andrew-zentner** [comment]
Nothing to worry about. I haven't updated those labels in months. I'm remaking all figures and labels today. Thanks though.

Andrew R. Zentner
Associate Professor &
Director of Graduate Studies
Department of Physics & Astronomy
The University of Pittsburgh

On Jun 20, 2016, at 9:05 AM, Frank C. van den Bosch <notifications@github.com<mailto:notifications@github.com>> wrote:

The labels above the 1D posteriors in Figs 1, 5 , 6 and 7 are NOT in agreement with the
percentiles quoted in the Table!!! Differences can be very substantial in some cases.....

##

**Comment by andrew-zentner** [comment]
Updated all labels with latest chain data. All labels should now be consistent with the values in the tables. Notice that all but one value had only a small change (<1%). The value that changed significantly was simply a typo. It should have been 0.06 rather than 0.6. I am continually running chains to ensure no weird things happen and will continue to update figures and table as needed until final publication.
