### ISSUE TITLE
figure cosmetics

### ISSUE THREAD

**Issue by aphearin** [andrew-zentner/abmcmc#9]
Suggestions from Frank: perhaps we can combine Figs. 2 3 and 4 in a single figure. 
Also, I suggest to indicate in the figure a caption stating what sample this is (so I don’t
have to get this information from the caption; this also applies to Figs 5-7). Also I suggest making the symbols a bit larger (for aesthetic reasons)

**Comment by aphearin** [comment]
Suggestions from APH: 
1. To make the labels of the numerical values of the axis values larger: `plt.xticks(size=15)` and similarly for `plt.yticks`. 
2. Use the `fontsize` keyword to make the font in the axis labeling appear larger: `plt.xlabel(r'$r_{\rm p}$  $[Mpc/h]$, fontsize=20)`
3. To fine-tune the vertical and horizontal range: `plt.ylim(ymin = 10, ymax=1e3)` and similarly for `plt.xlim`. 
4. The y-axis in the wp figures needs units of `Mpc/h`.

**Comment by andrew-zentner** [comment]
Changes font sizes, changed axis labels. Added units to both x and y axes. Also changed the Delta chi^2 range to 5.89, which is the change in chi^2 that contains 68% of the posterior if the posterior is a multivariate Gaussian. This seems to be a better representation of the variability of the fit, but actually make little to no practical difference in the plots because the chi^2 function varies very rapidly due to the small errorbars.
